---
title: "Recherche"
---

## Publications

Voir la liste de mes publications sur [mon profil Google Scholar](https://scholar.google.com/citations?user=sr4gTeMAAAAJ&hl=fr).

## Projets en cours

- [Projet WAIT4](https://www.pepr-agroeconum.fr/les-projets-finances/agroequipements/projets-cibles/wait4) : Intelligence artificielle et nouvelles technologies pour évaluer des indicateurs pertinents de bien-être pour des animaux confrontés aux défis de la transition agroécologique. Financement PEPR (~3M €). Participation au pilotage scientifique du projet.

- Projet PACE-COW : Développement de méthodes de caractérisation du comportement et des interactions sociales des bovins pour l'évaluation de la santé et du bien-être dans le cadre de la transition agroécologique. Thèse de [Joseph Allyndrée](https://www.linkedin.com/in/joseph-allyndree-904bb71b5/), financée par le projet WAIT4. Co-encadrement avec [Antoine Cornuéjols](https://antoinecornuejols.github.io/) et [Christine Martin](https://mia-ps.inrae.fr/index.php/christine-martin).

- [Projet Dynam'Heat](https://bioepar.angers-nantes.hub.inrae.fr/recherche/projet-en-cours/dynam-heat) : Dynamique et impact du stress thermique sur le comportement, les boiteries et les performances zootechniques des vaches laitières dans la Grand Ouest. Thèse d'Anne-Cécile Toulemonde. Directeur de thèse : [Raphaël Guatteo](https://bioepar.angers-nantes.hub.inrae.fr/l-unite/annuaire2/membres-g/guatteo-raphael). Co-encadrement avec [Yannick Le Cozler](https://pro.institut-agro-rennes-angers.fr/fr/yannick-le-cozler).


- [Projet ALONGE](https://idele.fr/alonge/) : Améliorer la longévité des vaches laitières par une gestion raisonnée et choisie des réformes et du renouvellement. Financement CASDAR.


## Projets terminés

- [Projet STOC free](https://stocfree.eu/) (2017-2020) : Méthodes pour quantifier la probabilité d'absence de maladies infectieuses non réglementées. Application à l'infection par le virus de la diarrhée virale bovine. Projet financé par l'[EFSA](https://www.efsa.europa.eu/fr). Co-responsable du WP1 sur le développement de méthodes.

- Réseau COST [SOUND Control](https://sound-control.eu/) : Surveillance des maladies non réglementées des bovins dans l'Union Européenne. Exploration, promotion, développement de méthodes visant à la standardisation des résultats  plutôt que celle des moyens mis en oeuvre. Responsable du WP3 sur les méthodes.

- Réseau COST [Harmony](https://harmony-net.eu/) : Nouveaux outils pour l'évaluation des tests et l'estimation de la prévalence des maladies. Responsable du WP4 sur l'évaluation de la probabilité d'absence d'une maladie.

## Packages R

- Package [STOC free](https://github.com/AurMad/STOCfree). Modèle de Markov caché pour l'estimation d'une probabilité d'infection à partir de résultats de tests longitudinaux obtenus dans le cadre d'un programme de surveillance. [Publication décrivant le modèle](https://peercommunityjournal.org/articles/10.24072/pcjournal.80/).

- [betadistapp](https://github.com/AurMad/betadistapp) : Application Shiny pour la détermination interactive des paramètres d'une [distribution Beta](https://fr.wikipedia.org/wiki/Loi_b%C3%AAta). Intérêt pour la définition de distributions a priori en [inférence bayésienne](https://fr.wikipedia.org/wiki/Inf%C3%A9rence_bay%C3%A9sienne).

- [logitnormdistapp](https://github.com/AurMad/betadistapp) : Application Shiny pour la détermination interactive des paramètres d'une [distribution normale sur une échelle logit](https://fr.wikipedia.org/wiki/Loi_logit-normale). Intérêt pour la définition de distributions a priori en [inférence bayésienne](https://fr.wikipedia.org/wiki/Inf%C3%A9rence_bay%C3%A9sienne).

## Habilitation à diriger des recherches

Mon [manuscrit d'HDR](https://hal.science/tel-04125958/) et la [présentation](https://aurmad.github.io/HDR) qui l'accompagne fournissent une bonne vue d'ensemble de mes activités de recherche. 